theme: jekyll-theme-slate

title: I am an engineer
description: 1. my attempts to build my own website 2. to meet more cool female or nontraditional backgrounds in engineering 
3. to increase my own sense of self confidence in tech/engineering
